### ISSUE TITLE
I followed the setup but am stuck on the blue loading screen

### ISSUE THREAD

**Issue by saxobroko** [codewired/FriendlyPix-Updated#1]
When i check in the developer console it says that my api key is invalid

**Comment by saxobroko** [comment]
error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/mnt/c/Users/Saxon Brooker/Documents/electron/FriendlyPix-Updated/node_modules/puppeteer/lib/Launcher.js:342:14)
    at Interface.helper.addEventListener (/mnt/c/Users/Saxon Brooker/Documents/electron/FriendlyPix-Updated/node_modules/puppeteer/lib/Launcher.js:331:50)
    at Interface.emit (events.js:203:15)
    at Interface.close (readline.js:397:8)
    at Socket.onend (readline.js:173:10)
    at Socket.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:915) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:915) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Error: Failed to launch chrome!
/mnt/c/Users/Saxon Brooker/Documents/electron/FriendlyPix-Updated/node_modules/puppeteer/.local-chromium/linux-637110/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/mnt/c/Users/Saxon Brooker/Documents/electron/FriendlyPix-Updated/node_modules/puppeteer/lib/Launcher.js:342:14)
    at Interface.helper.addEventListener (/mnt/c/Users/Saxon Brooker/Documents/electron/FriendlyPix-Updated/node_modules/puppeteer/lib/Launcher.js:331:50)
    at Interface.emit (events.js:203:15)
    at Interface.close (readline.js:397:8)
    at Socket.onend (readline.js:173:10)
    at Socket.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Done. Ready to deploy.


I am also receiving this error when deploying

**Comment by codewired** [comment]
Thanks for cloning this demo application and trying to explore the beautiful world of JavaScript, JQuery, Workbox and Firebase.

If you did setup a firebase account on www.firebase.com, then first of all you might need to log into the Google developers console and access the project that Firebase automatically created for you. Link to Google dev console => https://console.developers.google.com/apis/dashboard. When you locate your project make sure that you have enabled all required APIs as mentioned in the README file. After enabling the APIs it will be time to check if your environment has the required permissions. Inside of your console locate the Credentials page under API & Services Menu, Look for the OAuth 2.0 Client Id's and locate the one that was created by Google Services. Click on it to open the details page. In the details page make sure that your localhost and public site URIs is added to the Authorized JavaScript Origins and redirect URIs.

The second error while deploying might be an issue with your node version, i am using 10.16.3 for this repository.
Make these changes and let me know the result. you can also share a screen shot if need be. 

Good luck

**Comment by saxobroko** [comment]
I completely restarted and i got it deployed, also my problem was with the firebase-config.json file which for some reason had sdkConfig {} in it.
